# Generated by Django 4.1.6 on 2023-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataVegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('price', models.IntegerField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
