# Generated by Django 4.1.6 on 2023-03-28 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='product/img/')),
                ('seller', models.CharField(max_length=120)),
                ('number_seller', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=1000)),
                ('number_phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
