# Generated by Django 4.1.6 on 2023-03-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0002_user_vegetables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataVegetables',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
    ]
