# Generated by Django 4.1.7 on 2023-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
    ]
