# Generated by Django 4.1.7 on 2023-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0004_productcard_delete_vegetablecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
