# Generated by Django 4.1.6 on 2023-03-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0005_alter_profileuser_email_alter_profileuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.CharField(default='Екатеринбург', max_length=1000),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='age',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='number_phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
