# Generated by Django 4.1.7 on 2023-03-12 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Earth', '0006_remove_post_desc_post_user_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='data_of_pick',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
