# Generated by Django 4.1.6 on 2023-03-03 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Earth', '0006_profileuser_address_profileuser_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=5)),
                ('address', models.CharField(default='Екатеринбур', max_length=1000)),
                ('number_phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
