# Generated by Django 4.1.6 on 2023-03-03 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Earth', '0007_profile_delete_profileuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileUser',
        ),
    ]
