# Generated by Django 4.1.7 on 2023-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0007_remove_productcard_data_of_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
