# Generated by Django 4.1.7 on 2023-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0008_rename_profile_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
