# Generated by Django 4.1.7 on 2023-03-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0009_alter_productcard_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
