# Generated by Django 4.1.7 on 2023-03-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0010_alter_productcard_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='photo',
        ),
    ]
