# Generated by Django 4.1.7 on 2023-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earth', '0013_productcard_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='product/img/')),
                ('seller', models.CharField(max_length=120)),
                ('number_seller', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
